name: Deploy to NuxtHub
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"
      - run: pnpm install
      - run: pnpm build
      - uses: nuxthub/actions/deploy@main
        with:
          username: faeller
          project: karl-therapy-finder
          build-dir: .output
          token: ${{ secrets.NUXT_HUB_TOKEN }}